#!/usr/bin/python3 -I
# SPDX-License-Identifier: GPL-3.0-or-later
import sys
sys.dont_write_bytecode = True
sys.path.insert(0, '/usr/lib/plank-avp-relay')
from avp_relay.host_setup import main
raise SystemExit(main())
